/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "autenticacao.h"
#include "rsa.c"
#include "funcoes.c"

int *
troca_9_svc(void *argp, struct svc_req *rqstp)
{
	char hash[]="hash.txt";
    char numero[]="num.txt";
    char translado[]="translado.txt";

	static int  result;	
	long long msgCifrada,d;
	long long int n,hashTransporte,hashComparacao,mensagemCriptografada;
	// LENDO OS DADOS
	read(&mensagemCriptografada,&hashTransporte,&msgCifrada,&d,&n,translado);
	//printf("[Servidor]  %lld %lld %lld\n",mensagemCriptografada,d,n);	
	// DESCRIPTANDO OS DADOS	
	long long msgDescriptada =square_multiply(mensagemCriptografada, d, n);	
	// DESCRIPTANDO A ASSINATURA
	long long assinatura = square_multiply(msgCifrada, d, n);	
	// INSERINDO NUMERO PARA CALCULAR HASH
	insertNumero(assinatura,numero);
	// RODANDO A ROTINA PARA CALCULAR O HASHh
    rotina();	
	// RECUPERAR OS DADOS PARA A COMPARAR AS HASH
	readNumero(hash,&hashComparacao);	
	if(hashTransporte == hashComparacao){
		printf("Servidor Autenticado a assinatura\n");
		printf("[Mensagem Enviada] %lld\n",msgDescriptada);
		result = 1;		
	}else{
		result = 2;
		printf("Servidor Não Autenticado a assinatura\n");
	}
	return &result;
}
