/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "autenticacao.h"

bool_t
xdr_aux (XDR *xdrs, aux *objp)
{
	register int32_t *buf;

	 if (!xdr_quad_t (xdrs, &objp->mensageCriptografada))
		 return FALSE;
	 if (!xdr_quad_t (xdrs, &objp->hashMensagem))
		 return FALSE;
	 if (!xdr_quad_t (xdrs, &objp->hashDaMensagemCriptografada))
		 return FALSE;
	 if (!xdr_quad_t (xdrs, &objp->d))
		 return FALSE;
	 if (!xdr_quad_t (xdrs, &objp->n))
		 return FALSE;
	return TRUE;
}
