/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "autenticacao.h"
#include "rsa.c"
#include "funcoes.c"

aux *
troca_9_svc(aux *argp, struct svc_req *rqstp)
{
	static aux  result;
	char hash[]="hash.txt";
	long long int hashComparacao;
	/*
	printf("mensageCriptografada %ld\n",argp->mensageCriptografada);
	printf("hashMensagem %ld\n",argp->hashMensagem);
	printf("hashDaMensagemCriptografada %ld\n",argp->hashDaMensagemCriptografada);
	printf("d %ld\n",argp->d);
	printf("n %lld\n",argp->n);
	*/
	// DESCRIPTANDO OS DADOS	
	long long msgDescriptada =square_multiply(argp->mensageCriptografada, argp->d, argp->n);	
	//printf("%lld\n",msgDescriptada);
	// DESCRIPTANDO A ASSINATURA
	long long assinatura = square_multiply(argp->hashDaMensagemCriptografada, argp->d, argp->n);
	// INSERINDO NUMERO PARA CALCULAR HASH
	insertNumero(assinatura,hash);
	// RODANDO A ROTINA PARA CALCULAR O HASHh
    rotina();	
	// RECUPERAR OS DADOS PARA A COMPARAR AS HASH
	readNumero(hash,&hashComparacao);	

	if(argp->hashMensagem == hashComparacao){
		printf("Assinatura autenticada com sucesso\n");
		printf("[Mensagem Enviada] %lld\n",msgDescriptada);
		//result = 1;		
	}else{
		//result = 2;
		printf("Assinatura não autenticada.\n");
	}
	return &result;
}
