/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <time.h>
#include "autenticacao.h"
#include "rsa.c"
#include "funcoes.c"

	ll d, e,p,q,mensagem,msgCifradaDaHash;
    ll int n,m,hashMensagem,mensagemCriptografada;    
    char hash[]="hash.txt";

void
program_9(char *host)
{
	CLIENT *clnt;
	aux  *result_1;
	aux  troca_9_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, PROGRAM, VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

 	
	srand((unsigned)time(NULL));	    
	//seleciona os número p,q primos de forma aleatoria utilizando o algoritmo de Miller-Rabin.    
    escolherPrimos(&p,&q,&n);
    // Computa a função phi(n) = (p - 1) * (q - 1)
    m = (p - 1) * (q - 1);
    // Escolha um inteiro "e" , 1 < "e" < phi(n), tal que, "e" e phi(n) sejam primos
    // entre si.
    e = 2;
    primosEntreSI(&m,&e);        
    // "d" seja inverso multiplicativo de "e"
    d = modInverse(e, m);
    // MENSAGEM        
    int op=1;
    while(op){
    printf("Digite um número\n");
    scanf("%lld",&mensagem);

    // INSERINDO NO ARQUIVOO    
    insertNumero(mensagem,hash);    
    // RODANDO A ROTINA PARA CALCULAR O HASHh
    rotina();        
    // CARREGANDO O HASH
    readNumero(hash,&hashMensagem);        
    // AGORA VAMOS ENCRIPTAR A HASH DA MENSAGEM    
     msgCifradaDaHash = square_multiply(hashMensagem,e, n);
     // CIFRANDO A MESAGEM EM SÍ            
     mensagemCriptografada =square_multiply(mensagem,e, n); 
     
     troca_9_arg.mensageCriptografada=mensagemCriptografada;
     troca_9_arg.hashMensagem =hashMensagem;
     troca_9_arg.hashDaMensagemCriptografada=msgCifradaDaHash;
     troca_9_arg.d=d;
     troca_9_arg.n=n;    

	result_1 = troca_9(&troca_9_arg, clnt);
	if (result_1 == (aux *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("Deseja enviar mais uma mensagem ? [1-SIM OU 0-NÃO]\n");
	scanf("%d",&op);
}
printf("# Obrigado volte sempre #\n");	
printf("[ Desenvolvimento: Bruno Sousa e Francisco Antonio ]\n");
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	program_9 (host);
exit (0);
}
